version: '3.9'
services:
  db:
    image: mysql:8.0.39
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Admin123456
      MYSQL_DOCKER_PASSWORD: Docker123
      MYSQL_USER: docker
      MYSQL_DATABASE: spring_restful
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - starcode-network
  restful-spring-kotlin:
    image: kaioa1meida/restful-spring-kotlin
    restart: always
    build: .
    working_dir: /restful-spring-kotlin
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/spring_restful?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: Admin123456
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - starcode-network
networks:
  starcode-network:
    driver: bridge
