cors:
  originPatterns: http://localhost:3000,http://localhost:8080
file:
  upload-dir: /Users/kaioalmeida/code/upload
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_restful?useTimezone=true&serverTimezone=UTC
    username: root
    password: Admin123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  paths-to-match:
    -  /api/v1/**/**
    -  /auth/**
  swagger-ui:
    use-root-path: true